# check=skip=SecretsUsedInArgOrEnv
# Isnad — deployment image (T2).
#
# Build artifacts only. Deploying is the human's call, and Part 4's checklist
# must be green against the live host before a URL exists.

# ISNAD_VAULT_KEY_PATH is a filesystem path, not a credential — the linter
# matches on the substring "KEY" in the name. Every actual secret is absent from
# this file by design (see the block near USER below), so the skip directive on
# line 1 covers the name, not the practice.

# Keep this exact patch tag in sync with .python-version. CI may override it
# with an immutable digest (`--build-arg PYTHON_IMAGE=python@sha256:...`).
ARG PYTHON_IMAGE=python:3.11.15-slim
FROM ${PYTHON_IMAGE} AS build

WORKDIR /build
# Install into a virtualenv so the runtime stage can copy it without pip.
# --without-pip: the runtime stage copies this venv wholesale, and pip inside
# it would be copied too. pip is a build tool with advisories of its own and
# nothing at runtime installs anything, so it has no business in the image that
# faces the network. Dependencies are installed with the *system* pip into this
# venv via --python, which leaves the venv itself pip-free.
RUN python -m venv --without-pip /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# The lockfile, not requirements.txt: the image that ships is the one that was
# tested. Unpinned '>=' resolves to whatever is newest on demo morning (S8).
COPY requirements.lock.txt .
# --no-deps: the lockfile IS the complete closure (generated by pip freeze from
# a clean resolve), so nothing needs resolving. It also keeps pip out: the
# network-as-code SDK declares `pip==25.3` as a runtime dependency, which is a
# vendor packaging mistake — the SDK never imports pip and works with it absent —
# and pip 25.3 carries six advisories. Resolving deps here would drag it in and
# undo the --without-pip line above.
RUN /usr/local/bin/python -m pip --python /opt/venv/bin/python \
      install --no-cache-dir --no-deps -r requirements.lock.txt

# Fail the BUILD, not the demo, if the image cannot do what it claims. The
# previous image shipped without either SDK and nothing noticed, because
# LLMPlanner falls back to greedy on ImportError and 236 tests pass regardless.
RUN /opt/venv/bin/python -c "\
import importlib, sys; \
[importlib.import_module(m) for m in ('network_as_code', 'fastapi', 'segno')]; \
import importlib.metadata as md; \
sys.exit('pip must not be in the runtime venv' if any(d.metadata['Name'].lower() == 'pip' for d in md.distributions()) else 0)"



FROM ${PYTHON_IMAGE} AS runtime

# Non-root. The vault key is 0600 and owned by this user (S7b), so the process
# that reads it and the user that owns it are the same non-privileged account.
RUN useradd --system --create-home --uid 10001 isnad

# Remove the base image's system pip as well. The venv is already built
# --without-pip, but python:3.11-slim ships its own at /usr/local/bin, so
# `command -v pip` still found one — checked in the container rather than
# assumed. Nothing at runtime installs anything, so neither copy belongs here.
RUN python -m pip uninstall -y pip setuptools 2>/dev/null || true; \
    rm -rf /usr/local/lib/python3.11/site-packages/pip* \
           /usr/local/lib/python3.11/site-packages/setuptools* \
           /usr/local/bin/pip /usr/local/bin/pip3 /usr/local/bin/pip3.11

# The venv arrives without pip (see --without-pip above), so nothing in the
# running image can install anything. Verified with `command -v pip` in the
# container, not assumed — the first version of this file assumed it and was
# wrong, because `python -m venv` bootstraps pip into the venv by default.
COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY --chown=isnad:isnad app ./app
COPY --chown=isnad:isnad pyproject.toml ./
# `/lab` imports `demo.lab.runner` unconditionally and reads the recorded
# bundle from `demo/lab/artifacts/`, so an image without them answers /readyz
# happily and then fails that route (R10). Only `demo/lab` is copied: the
# merchant pilot and the fake operator are development harnesses, and a
# runtime image has no business carrying a fake operator.
#
# `demo/__init__.py` comes along because `demo.lab` is not importable without
# it. `demo/lab/runner.py` imports nothing outside `app` and `demo.lab`, and
# `_code_revision` already degrades honestly when there is no `.git` and no
# git binary — which is this image.
COPY --chown=isnad:isnad demo/__init__.py ./demo/
COPY --chown=isnad:isnad demo/lab ./demo/lab

# The bundled demo registry ships with its signature and public verification
# key. A fresh container can verify it independently of its own receipt key.
# Deployments replacing the registry must also supply its signature and override
# ISNAD_VAULT_TRUSTED_PUBLIC_KEYS with the signer they trust.
# Set ISNAD_REGISTRY_SIGNATURE_REQUIRED=true to reject a missing signature;
# the Render blueprint requires it for the reviewer demo.

# The persistent volume. Both paths below MUST be absolute and MUST live on it:
# a relative vault path plus a restart means a new signing key and every stored
# chain reporting invalid on stage (S6), and a lost pepper unbinds every chain
# from its subject (S5).
RUN mkdir -p /srv/isnad/.isnad \
 && chown -R isnad:isnad /srv/isnad \
 && chmod 700 /srv/isnad/.isnad
VOLUME ["/srv/isnad"]

ENV ISNAD_VAULT_KEY_PATH=/srv/isnad/.isnad/vault-key.pem \
    ISNAD_DATABASE_URL=sqlite:////srv/isnad/isnad.db \
    ISNAD_VAULT_TRUSTED_PUBLIC_KEYS=4034e169495122a893d8fe6738c2b0f54655fdfb6ec3c6d0eeb938d1330e7f9f \
    ISNAD_DEMO_MODE=false \
    ISNAD_PROVIDER=mock
# Deliberately NOT set here, because they are secrets and must come from the
# runtime environment — the app fails startup on the nac path without them:
#   ISNAD_MERCHANT_API_KEYS   ISNAD_SUBJECT_PEPPER   ISNAD_NAC_API_KEY
#   ISNAD_NAC_REDIRECT_URI    ISNAD_GEMINI_API_KEY

USER isnad
EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD python -c "import os,urllib.request,sys; port=os.environ.get('PORT','8000'); \
sys.exit(0 if urllib.request.urlopen(f'http://127.0.0.1:{port}/readyz',timeout=2).status==200 else 1)"

# --workers 1 is not optional: sessions, consent records, the SSE bus, the
# idempotency cache, the rate limiter and the vault singleton are all
# in-process. With more, an OAuth callback landing on a different worker than
# the one that issued the state fails nondeterministically and the console sees
# roughly 1/N of the events.
#
# --no-access-log because the OAuth `code` and `state` are query parameters, so
# the access log would record single-use authorization codes in cleartext (S13).
#
# No --reload.
# `sh -c` with `exec` rather than a bare exec-form CMD: managed hosts (Render,
# Cloud Run, Koyeb, Fly) hand the container a $PORT and expect it to be
# honoured. `exec` keeps uvicorn as PID 1, so SIGTERM still reaches it and the
# graceful shutdown below still means something.
CMD ["sh", "-c", "exec uvicorn app.main:app \
     --host 0.0.0.0 --port ${PORT:-8000} \
     --workers 1 --no-access-log --proxy-headers \
     --limit-concurrency 128 --timeout-graceful-shutdown 30"]
