"""Export the installed SDK's public contracts without making network requests.

This is documentation tooling. It does not load Isnad settings or any credential.
Schemas describe SDK acceptance, not necessarily the stricter operator contract.
"""
from __future__ import annotations

import ast
import inspect
import json
import textwrap
import typing
from importlib.metadata import version
from pathlib import Path

from network_as_code import NetworkAsCodeApi
from pydantic import TypeAdapter

ROOT = Path(__file__).resolve().parent.parent


def schema_for(annotation):
    return TypeAdapter(annotation).json_schema(by_alias=True)


def wire_contract(method):
    tree = ast.parse(textwrap.dedent(inspect.getsource(method)))
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
            continue
        if node.func.attr != 'request':
            continue
        info = {'path_expression': ast.unparse(node.args[0]) if node.args else None}
        for kw in node.keywords:
            if kw.arg in {'method', 'json', 'params', 'headers', 'content'}:
                info[kw.arg] = ast.unparse(kw.value)
        return info
    return {'unresolved': 'Inspect SDK raw method; no request call found'}


def short(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'anyOf' in schema:
        return ' | '.join(short(s) for s in schema['anyOf'])
    if 'enum' in schema:
        return 'enum: ' + ', '.join(map(str, schema['enum']))
    if 'const' in schema:
        return repr(schema['const'])
    if schema.get('type') == 'array':
        return 'list[' + short(schema.get('items', {})) + ']'
    return schema.get('format', schema.get('type', 'unconstrained'))


def main():
    # Constructing the client is local; no resource methods are invoked.
    client = NetworkAsCodeApi(api_key='documentation-only-placeholder')
    groups = {}
    for group in sorted(n for n in dir(type(client)) if not n.startswith('_')):
        resource = getattr(client, group)
        raw = getattr(resource, 'with_raw_response', None)
        if raw is None:
            continue
        operations = {}
        for name in sorted(n for n in dir(resource) if not n.startswith('_')):
            method = getattr(resource, name)
            if not callable(method):
                continue
            hints = typing.get_type_hints(method)
            sig = inspect.signature(method)
            params = {}
            for parameter, definition in sig.parameters.items():
                if parameter == 'request_options':
                    continue
                params[parameter] = {
                    'required_in_sdk': definition.default is inspect.Parameter.empty,
                    'schema': schema_for(hints[parameter]),
                }
            raw_method = getattr(raw, name)
            tree = ast.parse(textwrap.dedent(inspect.getsource(raw_method)))
            statuses = sorted({
                n.comparators[0].value for n in ast.walk(tree)
                if isinstance(n, ast.Compare) and isinstance(n.left, ast.Attribute)
                and n.left.attr == 'status_code' and len(n.comparators) == 1
                and isinstance(n.comparators[0], ast.Constant)
                and isinstance(n.comparators[0].value, int)
                and n.comparators[0].value >= 400
            })
            operations[name] = {
                'purpose': (inspect.getdoc(method) or '').split('\n\n')[0],
                'wire': wire_contract(raw_method),
                'parameters': params,
                'response_schema': schema_for(hints['return']),
                'explicit_error_statuses_in_sdk': statuses,
            }
        groups[group] = operations
    total = sum(len(g) for g in groups.values())
    payload = {
        'sdk_version': version('network-as-code'),
        'source': 'Installed network-as-code SDK public type hints and raw request AST',
        'network_calls': 0,
        'limits': 'SDK schema snapshot, not operator validation; purpose text comes from SDK. No actual response captures.',
        'operation_count': total,
        'groups': groups,
    }
    (ROOT / 'docs/NAC_SDK_CONTRACTS.json').write_text(json.dumps(payload, indent=2) + '\n')
    lines = [
        '# NaC installed SDK: complete operation index', '',
        f'SDK **{payload["sdk_version"]}**, **{len(groups)} resource groups**, **{total} operations**.', '',
        'Generated by `scripts/export_nac_contracts.py` using local SDK metadata only. **No API calls.**', '',
        'Read [the handoff reference](NAC_API_REFERENCE.md) for semantics, examples and integration rules.',
        'The [JSON companion](NAC_SDK_CONTRACTS.json) contains complete nested input/output schemas,',
        'wire mappings, enum values and declared error statuses for every operation.', '',
        '**Required means required by this SDK signature, not sufficient for the provider.**',
        'Optional identifiers may be conditionally mandatory for an authorization flow.',
        'Many SDK response properties default to null even when the catalog requires them.',
        'Enforce the versioned API contract explicitly; do not rely solely on SDK validation.', '',
    ]
    for group, operations in groups.items():
        lines += [f'## `{group}`', '']
        for name, operation in operations.items():
            wire = operation['wire']
            lines += [f'### `{group}.{name}`', '', operation['purpose'], '',
                      f'Wire method/path: `{wire.get("method", "unknown")} {wire.get("path_expression", "unknown")}`.', '',
                      '| SDK input | Required | Type / allowed values |', '| --- | --- | --- |']
            for name_, parameter in operation['parameters'].items():
                kind = short(parameter['schema']).replace('|', '\\|')
                lines.append(f'| `{name_}` | {parameter["required_in_sdk"]} | {kind} |')
            if not operation['parameters']:
                lines.append('| No operation-specific input | — | — |')
            response = operation['response_schema']
            lines += ['', f'Return type: {short(response).replace(chr(10), " ")}.', '']
            target = response
            if response.get('type') == 'array':
                target = response.get('items', {})
            if '$ref' in target:
                target = response.get('$defs', {}).get(target['$ref'].split('/')[-1], target)
            if 'properties' in target:
                lines += ['| JSON output field | SDK requires it | Type / allowed values |', '| --- | --- | --- |']
                for field, spec in target['properties'].items():
                    kind = short(spec).replace('|', '\\|')
                    lines.append(f'| `{field}` | {field in target.get("required", [])} | {kind} |')
                lines.append('')
            errors = ', '.join(map(str, operation['explicit_error_statuses_in_sdk'])) or 'generic SDK errors; inspect provider contract'
            lines += [f'Explicit SDK error branches: {errors}. Other statuses/transport failures remain possible.', '']
    (ROOT / 'docs/NAC_SDK_OPERATIONS.md').write_text('\n'.join(lines) + '\n')
    print(f'Exported {len(groups)} groups / {total} operations. Zero external calls.')


if __name__ == '__main__':
    main()
